# Generated by Django 5.2.13 on 2026-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rpps_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro RPPS'),
        ),
    ]
