# Generated by Django 5.2.13 on 2026-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_rpps_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes du médecin'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la consultation'),
        ),
    ]
