# Generated by Django 5.2.13 on 2026-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_license_number_remove_doctor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
